create schema if not exists eventhub;

create table if not exists eventhub.users (
    user_id bigint generated by default as identity primary key,
    username varchar(150) not null unique,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(254) not null unique,
    password_hash text not null,
    role varchar(20) not null default 'participant',
    status varchar(20) not null default 'active',
    phone varchar(20),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint users_first_name_length_chk
        check (char_length(trim(first_name)) between 2 and 50),

    constraint users_last_name_length_chk
        check (char_length(trim(last_name)) between 2 and 50),

    constraint users_email_not_blank_chk
        check (char_length(trim(email)) > 0),

    constraint users_role_chk
        check (role in ('admin', 'participant')),

    constraint users_status_chk
        check (status in ('active', 'deleted')),

    constraint users_phone_length_chk
        check (
            phone is null
            or char_length(trim(phone)) between 8 and 20
        )
);

create table if not exists eventhub.events (
    id bigint generated by default as identity primary key,
    title varchar(120) not null,
    description varchar(1000),
    price decimal(10,2) not null default 0.00,
    start_date timestamptz not null,
    end_date timestamptz not null,
    status varchar(20) not null,
    location varchar(150),
    max_participants integer not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint events_title_length_chk
        check (char_length(trim(title)) between 3 and 120),

    constraint events_description_length_chk
        check (
            description is null
            or char_length(description) <= 1000
        ),

    constraint events_location_length_chk
        check (
            location is null
            or char_length(trim(location)) <= 150
        ),

    constraint events_status_chk
        check (status in ('upcoming', 'ongoing', 'completed', 'cancelled')),

    constraint events_max_participants_chk
        check (max_participants > 0),

    constraint events_dates_chk
        check (end_date > start_date)
);

create table if not exists eventhub.registrations (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    user_id bigint not null,
    registered_at timestamptz not null default now(),

    constraint registrations_event_fk
        foreign key (event_id)
        references eventhub.events(id)
        on delete cascade,

    constraint registrations_user_fk
        foreign key (user_id)
        references eventhub.users(user_id)
        on delete restrict,

    constraint registrations_event_user_unique
        unique (event_id, user_id)
);

create index if not exists idx_events_start_date
    on eventhub.events(start_date);

create index if not exists idx_events_status
    on eventhub.events(status);

create index if not exists idx_users_status
    on eventhub.users(status);

create index if not exists idx_registrations_event_id
    on eventhub.registrations(event_id);

create index if not exists idx_registrations_user_id
    on eventhub.registrations(user_id);

create or replace function eventhub.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_users_set_updated_at on eventhub.users;
create trigger trg_users_set_updated_at
before update on eventhub.users
for each row
execute function eventhub.set_updated_at();

drop trigger if exists trg_events_set_updated_at on eventhub.events;
create trigger trg_events_set_updated_at
before update on eventhub.events
for each row
execute function eventhub.set_updated_at();

create table if not exists eventhub.image_url (
    id bigint generated by default as identity primary key,
    events_id bigint not null,
    image_url text not null,
    created_at timestamptz not null default now(),

    constraint image_url_event_fk
        foreign key (events_id)
        references eventhub.events(id)
        on delete cascade,

    constraint image_url_not_blank_chk
        check (char_length(trim(image_url)) > 0)
);

create index if not exists idx_image_url_events_id
    on eventhub.image_url(events_id);